version: "3.8"

services:
  server:
    image: 503561454740.dkr.ecr.ap-south-1.amazonaws.com/pockity/test
    ports:
      - "8080:8080"
      - "5432:5432"
    env_file:
      - .env.test
    restart: unless-stopped
