version: "3.8"

services:
  server:
    image: 503561454740.dkr.ecr.ap-south-1.amazonaws.com/pockity/prod
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    restart: unless-stopped
